### ISSUE TITLE
Missing SerialFirmata

### ISSUE THREAD

**Issue by soundanalogous** [MrYsLab/FirmataExpress#1]
I'm sure you're aware, but this port is missing [SerialFirmata](https://github.com/firmata/arduino/blob/master/utility/SerialFirmata.h) (added in Firmata 2.5.0). Doesn't look like that will cause any issues though since all references to the feature are protected behind an ifdef.

**Comment by MrYsLab** [comment]
Hi @soundanalogous. Thanks for the comment. I did consider adding it but decided not to in the end. My reasoning is two-fold. First, my view, perhaps incorrectly, is that SerialFirmata is an optional part of StanfdardFirmata, and since it is not enabled by default, is not actually part of it. Leaving it out of my distribution, but leaving in the #ifdef's in the code would help alert me if one of my users wanted to take advantage of the feature. Since it would not compile, they would probably generate an issue to alert me to that fact.

The second reason and probably more important is that I own a very limited set of Arduino board types, and therefore would not be able to test the feature adequately. If requested to add the support for the Pymata Express client, I would need a user willing to help test things out. In that case, I would probably reconsider my decision and implement the serial feature in FirmataExpress and support it in Pymata Express.

So, for now, I am going to leave things as is and will close this issue but may reconsider this decision at a later date.

Thanks again for your comment.
