### ISSUE TITLE
Sorry not an issue break the rules and ask a question? 

### ISSUE THREAD

**Issue by rooferdave** [MrYsLab/FirmataExpress#16]
I have firmata-express setup and working with mega 2560. Using home assistant supervisor. 
Can I use the home assistant firmata intergration using dht11 sensors, What would the configuration settings be in the config.yaml.
example, one of my sensors:
binary_sensors:
      - name: firmata2_motion_laundryroom_washer
        pin_mode: PULLUP
        pin: 15
        negate: false.
What would the dht11 sensor fall under and pin mode, etc...

Sorry for me asking here, I have  been googling for days with no luck or any examples.

**Comment by MrYsLab** [comment]
No problem with the question. First, I was not aware that home-assistant was using FirmataFirmata express.

Home-assistant is not a package I use,  but hopefully, I can provide some insight into answering your question.

Since [home-assistant ](https://github.com/home-assistant)has many components within GitHub, would you happen to know in which component the firmata support exists? This may help me understand things better if my answer does not solve your problem.

Looking at the [home-sensor documentation](https://www.home-assistant.io/integrations/firmata/#sensor), the pin mode needs to be set to [PIN_MODE_DHT](https://github.com/MrYsLab/FirmataExpress/blob/7149014763f3e0395ca9f718c4b523c56c2065e1/FirmataConstants.h#L113). Since I do not know where home-assistant is picking up pin types, it may or may not know what to do with this pin type. This pin type requires that a callback function be specified, similar to any other input sensors needed, but the report format is specific to the DHT.

My guess is that the home-assistant firmata support code would need to be modified to support DHT devices.

Please let me know if any of this helps. You may need to contact the developer who implemented the Firmata support to update the home-assistant code to support DHT devices.

**Comment by MrYsLab** [comment]
I found the [code](https://github.com/home-assistant/core/tree/dev/homeassistant/components/firmata). It will need modification to support DHT devices. I am not knowledgeable enough about home-assistant to know how difficult this would be. Perhaps, create an issue in home-assistant.

**Comment by rooferdave** [comment]
You programmers are gods!

**Comment by MrYsLab** [comment]
Really? Not quite, just nerds ;-) 
 Your question has piqued my interest in home-assistant. I am in the middle of several other projects, but I am adding home-assistant interfaces to my to-do list for my [Telmetrix](https://mryslab.github.io/telemetrix/) libraries. Telemetrix is similar to Firmata, but is much simpler and takes a modern approach. Currently, I have Telemetrix interfaces for Arduino, ESP8266, Raspberry Pi Pico, Arduino Nano 2040, and STM32. I am working on ESP32 Bluetooth BLE and Wifi. My goal would be to open up all supported devices instead of the few currently offered for Firmata. Not sure when I will get around to doing this, but stay tuned.

**Comment by rooferdave** [comment]
I want to get rid of my wi-fi microcontrollers for an all hard-wired system and all that i have left are the dht sensors that are currently connected to a sparklefun esp_32. Currently  Im playing around  on an stm32F446 /w your sketch running. Thanks Again!
