### ISSUE TITLE
verify firmataexpress is uploaded correctly by startup LED blink

### ISSUE THREAD

**Issue by gasolin** [MrYsLab/FirmataExpress#2]
according to https://www.pjrc.com/teensy/td_libs_Firmata.html

`
When Firmata boots, it blinks the LED in a pattern to let you know it's running, and give you the version number. Checking the LED blink is a simple way to verify your Teensy is running Firmata
`

this is a very handy way to verify the right version is installed and running. Will be nice to have it for FirmataExpress

**Comment by MrYsLab** [comment]
I removed the blinking version number because it actually can be more confusing than not. It also adds more delay to the startup. Since there are many flavors of Firmata, and they may share the same version number, the fact that a version is being blinked provides very little useful information. One still does not know if the version of Firmata loaded is the one that is needed.

That is one of the reasons that I added an identification byte to FirmataExpress.  SinceFirmataExpress is intended to be used by pymata-express, a pymata-express application will only start if it finds FirmataExpress with the correct ID. 

The other reason for the ID byte is that one can have multiple Arduino's connected to the PC, each running a different version of Firmata and the pymata-express application will find and use the correct one.

Please let me know your thoughts about this.

**Comment by gasolin** [comment]
But without that, there's no way to visually spot if the firmware is flashed successfully.

The general use case is not to differentiate with the other firmata version. The student will get a pre-flashed board, some times the board is not flashed by mistake or something broken. 
The teacher can ask students to check if the LED is blinked when power on, to make sure the firmataexpress is ready (no matter what version it is) without open the console log.

**Comment by MrYsLab** [comment]
I am not going to officially support this feature because it will change the startup time for existing users. However, I created a branch in this repository called [blink_version](https://github.com/MrYsLab/FirmataExpress/tree/blink_version).

This branch will turn on blinking. I have added a [.zip file ](https://github.com/MrYsLab/FirmataExpress/raw/blink_version/FirmataExpress.zip) that can be loaded into the Arduino IDE by 
opening the Arduino IDE, then clicking on "Sketch" and then "Include Library", and finally select 
"Add .Zip library".

I am closing this issue, but if necessary, it can be reopened.
