### ISSUE TITLE
Option to get all ultrasonic data in one update

### ISSUE THREAD

**Issue by mklomp** [MrYsLab/FirmataExpress#8]
The current implementation is sending the data of just one ultrasonic sensor at a time ([switching between number of sensors](https://github.com/MrYsLab/FirmataExpress/blob/1425a84ff145128454f192cf5eb6d093fe9f52ea/examples/FirmataExpress/FirmataExpress.ino#L1121)). Therefore the update rate of one sensor drops when you have muliple sensors. This is usefull when they are facing the same way to account for inference, but not needed when the two sensors face a different way. It would be nice to have an option to set whether you want the sonars to update the way they do now, or have them all at each updaterate. Easy solution would be a boolean setting this feature on or off. Advance feature would be that you provide a list of sensro-id which should not be updated at the same time (because they might interfere).

**Comment by MrYsLab** [comment]
Thanks for the feature request. I do not have the bandwidth to explore this at the moment. There is not a lot of room left in the sketch when using the Uno, so it may not be possible to add the support for your suggestion. The feature would have to be implemented as an all or nothing approach. That is a user would only be able to run in the current mode, or the additional mode that you suggest. Supporting a mixed configuration of both modes would add a lot of complexity and code to maintain.

**Comment by MrYsLab** [comment]
I reviewed your request, and although a good idea, it is somewhat out of the mainstream. Because of the limited amount of space left to add new features to FirmataExpress, I will not be implementing this. If you wish to fork and implement things on your own and need help with modifying either FirmataExpress and pymata4/pymata-express, I would be glad to assist if I can.

Again thanks for your suggestion.
